config/routes.rb
Wangzifeng::Application.routes.draw do
  get "home/index"
  get "blog", to: "blog#index"

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	def index
		@index = "Blog"
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@name = "wangzifeng"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog/index.html.erb
<div class="tumblr">
<iframe iframe width="100%" height="100%" frameborder="0" src="http://wangzifeng.tumblr.com/">
	<p>http://wangzifeng.tumblr.com/</p>
</iframe>
</div>

app/views/home/index.html.erb
<div>
	<div class="container">
		<div class="row">
            <div class="col-md-12">
		<%= image_tag "wangzifeng.jpg", class: "img-responsive"%>
			</div>
		</div>
	</div>
</div>

<div>

<h1 class="text-center">Frank Wang 王子丰</h1>
  <div>~</div>
  <p class="lead">I make interesting stuff, I travel around the world. I'm the creator of <a href="http://www.nodeq.com">nodeq.com</a></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Frank Wang - Wang Zi Feng</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">  
  <meta name="description" content="I make interesting stuff, I travel around the world. I'm the creator of nodeq.com">
  <meta name="author" content="Frank Wang">
  <meta name="google-site-verification" content="zYPaP9rYZyItKJCcZdrSR_IKSPsn0Fh1ctoFAQXVSCs" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

      <div class="navbar navbar-static-top" role="navigation">
      <div class="container">
        <div class="nav">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="./"><h4>Home</h4></a></li>
            <li class="active"><a href="<%= blog_path %>"><h4>Blog</h4></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<div class="container text-center">
	<%= yield %>
</div>

<div class="footer">
<div class="container text-center">
<div>~</div>
<h4><strong>Find Me</strong></h4>
  <span><a href="https://twitter.com/wangzifeng">Twitter</a></span>
  <span><a href="http://instagram.com/wangzifeng">Instagram</a></span>
  <span><a href="http://wangzifeng.tumblr.com/">Tumblr</a></span>
  <span><a href="http://www.linkedin.com/in/wangzifeng">Linkedin</a></span>
  <span><a href="https://angel.co/wangzifeng">AngelList</a></span>

<div>~</div>
  	<span><strong>COPYRIGHT © 2008 - <%= Time.now.year %> wangzifeng.com </strong></span>	
</div>
</div>

</body>
</html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48271904-1', 'wangzifeng.com');
  ga('send', 'pageview');

</script>